import Head from 'next/head';
import React from 'react';
import { Layout, Posts } from '../components';

export default function blog() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input type="text" className="searchInput" />
      <Posts
        title={'Detta är ett blogg inlägg'}
        content={
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis'
        }
      />
      <Posts
        title={'Detta är ett blogg inlägg'}
        content={
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis'
        }
      />
      <Posts
        title={'Detta är ett blogg inlägg'}
        content={
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis'
        }
      />
    </Layout>
  );
}
