import Head from 'next/head';
import React from 'react';
import { Layout } from '../components';

export default function contact() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>contact</h1>
    </Layout>
  );
}
